sudo: required
dist: bionic # (18.04)

language: cpp

cache: ccache

addons:
  apt:
    update: true

services:
  - mysql
  - docker

git:
  depth: 10

stages:
  - prepare_cache
  - run
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "XVzKZ6XaceZme9zDbVhXvS7+dxNFlcDY89EJugJaWJbj/0V9CS9zo1BGFduUMQBjuCjQSJkbJn0n6Bodt2YVvztirutSl6Iv6c7guzWZCJxd6OHBNpCsgipABYT468GRzbti5YA+FeG34d3COaBCCr/Pugt4sHa+5jevVFlHv8LWCBaDcWViSAng0vlk8X0iLz4HGxM8SSvtUPqTEEElT996ZLL9TgS00e/yDPcEHnz6DG6x6BVQdlHt+C8TD+gOo0b/sLfaXh9ReCChBj1asMA6Yv4gx8OlaWS4HXLxTbIfxfHntT/heMsO8gK2aRtwGsv80VSmB6BOqWnt6CxXOGjNMeUZJE+krJUAHr7VTP8Iz0ccPT1MsEaav5yw0jZiWXt5RLCJ8P2QvORd4LPv009aDU396uSgU+iOH6L77mAO7YugCwQs6NXU47Zj6vShOCKRdZlEXYyW9isi3Q/QTa/MqaLM2T/wFtcEenv3y4kHpwKlnIAZ99ToNdG0oaQUgq8yWo6O1WARAfD1qQ6Jyn8bd96LXi/SamHgV5oaKteQ5LvW2vgdB0UUbdNkD6D3FvaHjoQrRylsTKs9TOrDylewJUL0Z5qsLsm7/prylvwLcRhqQahprPTkIUdauT9snkocBxd+VGDLEql7ICx84J3pt5JPg3QXHytuxUe/ak0="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "azerothcore/azerothcore-wotlk"
      description: "AzerothCore Coverity"
    notification_email: "yehonal.azeroth@gmail.com"
    build_command: "./acore.sh 'compiler' 'all'"
    branch_pattern: coverity_scan

jobs:
  include:
    - stage: prepare_cache
      env: TRAVIS_BUILD_ID="1"
      before_install:
          - git config user.email "azerothcorebot@gmail.com" && git config user.name "AzerothCoreBot"
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd bin/; fi
          # import pending sql
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then source acore-db-pendings; fi
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd ..; fi
          # push changes to git if any
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git fetch --unshallow; fi
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git checkout $TRAVIS_BRANCH; fi
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ -n "$GITHUB_API_KEY" ]]; then git add -A . && git diff --cached --quiet || git commit -am "Import pending SQL update file..." -m "Referenced commit(s):$COMMIT_HASH" && git push https://$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_BRANCH; fi
          # sync staging with master
          # - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ -n "$GITHUB_API_KEY" ]]; then git fetch origin staging:staging && git checkout staging && git merge --no-edit master && git push https://$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG.git staging; git checkout master; fi
          - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh OFF
        - source ./apps/ci/ci-install-modules.sh
      script:
        - source ./apps/ci/ci-compile.sh

    - stage: run
      env: TRAVIS_BUILD_ID="1"
      before_install:
        - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh ON
        - source ./apps/ci/ci-install-modules.sh
        - source ./apps/ci/ci-import-db.sh
      script:
        - source ./apps/ci/ci-compile.sh
        - source ./apps/ci/ci-worldserver-dry-run.sh

    - stage: prepare_cache
      env: TRAVIS_BUILD_ID="2"
      before_install:
          - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh OFF
        - source ./apps/ci/ci-install-modules.sh
      script:
        - source ./apps/ci/ci-compile.sh

    - stage: run
      env: TRAVIS_BUILD_ID="2"
      before_install:
        - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh ON
        - source ./apps/ci/ci-install-modules.sh
      script:
        - source ./apps/ci/ci-compile.sh

    - stage: run
      env: TRAVIS_BUILD_ID="3"
      script:
        - ./apps/ci/docker/ci-docker-config.sh
        - ./bin/acore-docker-generate-etc
        - ./bin/acore-docker-build-no-scripts
        - docker-compose up -d ac-database
