version: '3.2'

services:

  ac-database:
    image: acore/ac-database:latest
    restart: unless-stopped
    networks:
      - ac-network
    ports:
      - ${DB_EXTERNAL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: ac-database
        target: /var/lib/mysql

  ac-assets:
    image: acore/ac-assets:latest
    volumes:
      - type: volume
        source: ac-assets
        target: /azeroth-server/data

  ac-worldserver:
    image: acore/ac-worldserver:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - ac-network
    ports:
      - ${WORLD_EXTERNAL_PORT:-8085}:8085
      - ${SOAP_EXTERNAL_PORT:-7878}:7878
    volumes:
      - type: bind
        source: ${WORLDSERVER_LOGS:-./docker/worldserver/logs}
        target: /azeroth-server/logs
      - type: bind
        source: ac-assets
        target: /azeroth-server/data
    depends_on:
      - ac-database

  ac-authserver:
    image: acore/ac-authserver:latest
    restart: unless-stopped
    networks:
      - ac-network
    ports:
      - ${AUTH_EXTERNAL_PORT:-3724}:3724
    volumes:
      - type: bind
        source: ${AUTHSERVER_LOGS:-./docker/authserver/logs}
        target: /azeroth-server/logs
    depends_on:
      - ac-database

volumes:
  ac-database:

networks:
  ac-network:
