name: coverity-scan
on:
  push:
    branches:
    - coverity_scan
  pull_request:
    branches:
    - coverity_scan

jobs:
  latest:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone AzerothCore
        run: git clone --depth=1 --branch=coverity_scan https://github.com/azerothcore/azerothcore-wotlk .

      - name: Install deps
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          bash ./acore.sh install-dep
          sudo apt-get install libreadline-dev

      - name: Download Coverity Build Tool
        run: |
          set -x
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=azerothcore%2Fazerothcore-wotlk" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Build with cov-build
        run: |
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          mkdir build
          cd build
          cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=1 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=0 -DSCRIPTS=1 -DSERVERS=1 -DWITH_PERFTOOLS=0 -DENABLE_EXTRA_LOGS=1 -DCMAKE_BUILD_TYPE=Debug
          echo "Using # cpu core:"`nproc`
          cov-build --dir cov-int make -j`nproc` -k

      - name: Submit the result to Coverity Scan
        run: |
          cd build
          tar czvf acore.tgz cov-int
          curl \
            --form token=$TOKEN \
            --form email=yehonal.azeroth@gmail.com \
            --form file=@acore.tgz \
            --form version=trunk \
            --form description="Coverity scan for azerothcore" \
            https://scan.coverity.com/builds?project=azerothcore%2Fazerothcore-wotlk
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
