name: coverity-scan
on:
  push:
    branches:
    - coverity_scan
  pull_request:
    branches:
    - coverity_scan

jobs:
  latest:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: coverity_scan
          fetch-depth: 3

      - name: Install deps
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          bash ./acore.sh install-deps

      - name: Build with cov-build
        run: |
          echo "COVERITY_TOKEN=\"$COVERITY_TOKEN"" >> ./conf/config.sh
          echo "COVERITY_TOKEN=\"$COVERITY_EMAIL"" >> ./conf/config.sh
          bash ./acore.sh tools coverity_scan
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_EMAIL: ${{ secrets.COVERITY_SCAN_EMAIL }}

